export const AI_HOTSPOT_CONFIG = {
  refresh: {
    defaultCooldownMinutes: 30,
    archiveDays: 20,
    dailyArchiveDays: 45,
    trashRetentionDays: 14,
    defaultTranslateMaxNew: 80,
  },
  http: {
    timeoutMs: 45000,
    retries: 2,
    retryDelayMs: 800,
    userAgent: 'Mozilla/5.0 (LingMo AI Hotspots)',
  },
  rss: {
    maxConcurrency: 8,
  },
  filter: {
    aiKeywords: [
      'aigc',
      'llm',
      'gpt',
      'claude',
      'gemini',
      'deepseek',
      'openai',
      'anthropic',
      'hugging face',
      'transformer',
      'prompt',
      'diffusion',
      'agent',
      '多模态',
      '大模型',
      '人工智能',
      '机器学习',
      '深度学习',
      '智能体',
      '算力',
      '推理',
      '微调',
    ],
    techKeywords: [
      'robot',
      'robotics',
      'embodied',
      'vision',
      'chip',
      'gpu',
      'cuda',
      'developer',
      'open source',
      '开源',
      '技术',
      '编程',
      '芯片',
      '机器人',
      '具身',
    ],
    noiseKeywords: ['娱乐', '明星', '八卦', '足球', '篮球', '彩票', '旅游', '美食', 'github.com', 'github.io', 'githubusercontent'],
    commerceNoiseKeywords: ['淘宝', '天猫', '京东', '拼多多', '促销', '优惠', '补贴', '下单'],
    trustedAiSourceIds: [
      'aihot', 'ai-hot-rss', 'aibase', 'aihubtoday',
      'newsnow', 'wechat-rss', 'buzzing', 'zeli', 'techurls',
      'lobsters', 'ithome', 'huxiu', '36kr', 'sspai',
    ],
    enSignalPattern: /(?<![a-z0-9])(ai|aigc|llm|gpt|openai|anthropic|deepseek|gemini|claude|robot|robotics|machine learning|artificial intelligence|transformer|diffusion|agent)(?![a-z0-9])/i,
  },
}
